Update DDWiper
Added error for when user forgot to actually connect a device or device was not recognised.

diff --git a/DDWiper b/DDWiper
--- a/DDWiper
+++ b/DDWiper
@@ -1,5 +1,12 @@
 #!/bin/bash
 intHDD=$( lsblk|grep SWAP|cut -c 7,8,9 )
+if [[ $( lsblk|grep -v $intHDD|grep -v sr0|grep -v NAME ) = '' ]]
+then
+	echo ""
+	echo ""	
+	echo "No block device found.  Aborting..."
+	exit 1
+fi
 while ! [[ $choice =~ ^sd[a-z]$ ]]
 do
 	clear
