Add files via upload

diff --git a/SATAWiper b/SATAWiper
--- a/SATAWiper
+++ b/SATAWiper
@@ -23,6 +23,10 @@ else
 	then
 		echo "Device doesn't appear to support SATA commands.  Is it a USB?  Aborting..."
 		exit 1
+	elif [[ $( hdparm -I /dev/$choice|grep SECURITY ) = '' ]]
+	then
+		echo "Device doesn't appear to support the SECURITY ERASE command.  Aborting..."
+		exit 1
 	else
 		if [[ $( hdparm -I /dev/$choice|grep frozen|cut -f 2 ) = 'not' ]]
 		then
